import { defineConfig } from 'astro/config';

export default defineConfig({
  site: 'https://makenewnc.org',
  compressHTML: true,
  redirects: {
    // WordPress legacy paths
    '/messages': '/',
    '/messages/': '/',
    '/our-pastor': '/our-story',
    '/our-pastor/': '/our-story',
    '/privacy-policy': '/privacy',
    '/privacy-policy/': '/privacy',
    '/events': '/locations',
    '/events/': '/locations',
    // Short internal slugs from prototype phase
    '/about': '/what-were-about',
    '/about/': '/what-were-about',
    '/story': '/our-story',
    '/story/': '/our-story',
    '/beliefs': '/our-beliefs',
    '/beliefs/': '/our-beliefs',
    '/ctpt': '/christian-themes-for-privileged-teens',
    '/ctpt/': '/christian-themes-for-privileged-teens',
    // Prototype tree → production (bookmark preservation)
    '/prototypes': '/',
    '/prototypes/': '/',
    '/prototypes/a': '/',
    '/prototypes/a/': '/',
    '/prototypes/b': '/',
    '/prototypes/b/': '/',
    '/prototypes/c-dark': '/',
    '/prototypes/c-dark/': '/',
    '/prototypes/c': '/',
    '/prototypes/c/': '/',
    '/prototypes/c/about': '/what-were-about',
    '/prototypes/c/about/': '/what-were-about',
    '/prototypes/c/story': '/our-story',
    '/prototypes/c/story/': '/our-story',
    '/prototypes/c/beliefs': '/our-beliefs',
    '/prototypes/c/beliefs/': '/our-beliefs',
    '/prototypes/c/ctpt': '/christian-themes-for-privileged-teens',
    '/prototypes/c/ctpt/': '/christian-themes-for-privileged-teens',
    '/prototypes/c/locations': '/locations',
    '/prototypes/c/locations/': '/locations',
    '/prototypes/c/events': '/locations',
    '/prototypes/c/events/': '/locations',
  },
});
